---
name: kspaceduel
version: 17.08.1
summary: Space Arcade Game
description: In KSpaceDuel each of two possible players control a satellite spaceship
    orbiting the sun. As the game progresses players have to eliminate the opponent's
    spacecraft with bullets or mines.
confinement: strict
grade: stable
apps:
    kspaceduel:
        command: kf5-launch kspaceduel
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kspaceduel
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kspaceduel:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libkf5kdegames-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kspaceduel-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
